[master]
vm-master-0 ansible_host=4.213.163.254

[workers]
vm-worker-0 ansible_host=10.0.1.4

[workers:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q ubuntu@4.213.163.254 -i /home/mgamal/terraform/Azure-dev-K8s/azure_dev_k8s_rsa -o StrictHostKeyChecking=no"'



[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/mgamal/terraform/Azure-dev-K8s/azure_dev_k8s_rsa
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

